### ISSUE TITLE
xiFDR use for XlinkX FDR estimation

### ISSUE THREAD

**Issue by TaraBartolec** [Rappsilber-Laboratory/xiFDR#19]
Dear xiFDR team,

I would like to use this tool to estimate the FDR, at different levels of redundancy, of crosslinking data searched with XlinkX.

Unfortunately, the crosslink spectral match (CSM) output table is problematic to use with xiFDR. There are two main issues:
1. Decoy hits are noted by just "isDecoy" = TRUE as opposed to isDecoyPeptide1 and isDecoyPeptide2. This includes decoy hits that involving one hit to the target database and one hit to the reverse database. 
2. Decoy hits lack any information of the protein each peptide belongs to. This means I cannot fill in information on the accession for each peptide, and the peptide location within each protein.

Is there any workaround for this? I am mainly interested in providing an estimate of the FDR at the PPI level. 

I have attached an example file.

Thank you,
Tara

**Comment by TaraBartolec** [comment]
[01052019_Nuc_F1840_PD23_S40D4_CSMs.txt](https://github.com/Rappsilber-Laboratory/xiFDR/files/3678910/01052019_Nuc_F1840_PD23_S40D4_CSMs.txt)

**Comment by lutzfischer** [comment]
At the moment that is not possible. 

One could fake things into the file to somewhat get an estimate, by adding random  protein names for the decoys. If it is an intra-match twice the same - otherwise two different ones.
One problem is that we need the information if it is a target-decoy or decoy-decoy match. So we would need to look up the peptide if - considering the digestion rules - it could have been derived from a target protein. Then you could also add the "correct" protein. 
Anyway we would need to look up the peptide positions anyway - as we don't have them in the file.

Seeing that you have some experience with R you could try.

I will probably not have time soonish to look into this in more detail.

**Comment by TaraBartolec** [comment]
Hi Lutz,

Thanks for the information - I have had a go at wrangling the XlinkX output in R and managed to get it into a format for xiFDR.

Best,Tara
